/**
 * Emit dist/theme.css — the CSS-only consumption path — and copy the hand-
 * written sheets into dist so the exports map resolves.
 *
 * TEMPORARY. `glyph theme build` (ORI-425) replaces this whole script with a
 * one-line change to package.json's build script. Until then this does the same
 * job with the public token API, so `pnpm build` produces everything the
 * exports map promises.
 */
import { copyFile, writeFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { themeToCSSVars } from '@originsuite/glyph/tokens';
import { brandTheme } from '../dist/index.js';

const DIST = 'dist';
const SRC = 'src';

// The static sheet is scoped to `.theme-<name>`, which is what a CSS-only
// consumer wraps its markup in. ThemeProvider stamps its own unique class
// instead, so the two never collide.
const selector = `.theme-${brandTheme.name}`;
const vars = themeToCSSVars(brandTheme.tokens);
const body = Object.entries(vars)
  .map(([name, value]) => `  ${name}: ${value};`)
  .join('\n');

await writeFile(
  join(DIST, 'theme.css'),
  `/* Generated by scripts/build-css.mjs — do not edit. */\n${selector} {\n${body}\n}\n`,
  'utf8'
);

for (const file of await readdir(SRC)) {
  if (file.endsWith('.css')) await copyFile(join(SRC, file), join(DIST, file));
}

if (existsSync(join('assets', 'fonts'))) {
  console.log('assets/fonts exists — copy it into dist/fonts/ when you self-host.');
}

console.log(`wrote ${DIST}/theme.css (${Object.keys(vars).length} tokens) for ${selector}`);
